# Catalogue Management Service Spring Reactive Restful APIs
info:
  app:
    name: Catalogue Management Service
    description: Catalogue Management Service Spring Native Build Reactive Restful APIs
    version: 1.0.0

# Spring boot actuator configurations
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics

# Configure Logging
logging:
  level:
    root: INFO
    com.toomuch2learn: DEBUG
    org.springframework: INFO
    org.apache.catalina: ERROR

# Display auto-configuration report when running a Spring Boot application
#debug: true

# Configure Spring specific properties
spring:

  # Properties for configuring jackson mapper
  jackson:
    mapper:
      # For enums, consider case insensitive when parsing to json object
      accept-case-insensitive-enums: true
    #serialization:
    #  write-dates-as-timestamps: false

  resources:
    add-mappings: false